version: '3'
services:
  redis-cache:
    container_name: redis-cache
    image: redis:alpine

  redis-queue:
    container_name: redis-queue
    image: redis:alpine

  redis-socketio:
    container_name: redis-socketio
    image: redis:alpine

  frappe:
    container_name: frappe-bench
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ./workspace:/workspace:cached
    working_dir: /workspace/development
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
      
  #pgsql:
  #   container_name: pgsql
  #   image: postgres:14.0
  #   environment:
  #    POSTGRES_PASSWORD: frappe
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
       
  mariadb:
     container_name: mariadb
     image: mariadb:10.9.3
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: rootdocker
     volumes:
        - ./db/:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
     ports:
        - 3306:3306
