version: '3'
services:
  redis-cache:
    container_name: redis-cache
    image: redis:alpine

  redis-queue:
    container_name: redis-queue
    image: redis:alpine

  redis-socketio:
    container_name: redis-socketio
    image: redis:alpine

  frappe:
    container_name: frappe-bench
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ./workspace:/workspace:cached
    working_dir: /workspace/development
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005

